# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oreo/Projects/physics-engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oreo/Projects/physics-engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oreo/Projects/physics-engine/CMakeFiles /home/oreo/Projects/physics-engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oreo/Projects/physics-engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/oreo/Projects/physics-engine/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PhysicsEngine

# Build rule for target.
PhysicsEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PhysicsEngine
.PHONY : PhysicsEngine

# fast build rule for target.
PhysicsEngine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/build
.PHONY : PhysicsEngine/fast

src/graphics/render.o: src/graphics/render.c.o
.PHONY : src/graphics/render.o

# target to build an object file
src/graphics/render.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/graphics/render.c.o
.PHONY : src/graphics/render.c.o

src/graphics/render.i: src/graphics/render.c.i
.PHONY : src/graphics/render.i

# target to preprocess a source file
src/graphics/render.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/graphics/render.c.i
.PHONY : src/graphics/render.c.i

src/graphics/render.s: src/graphics/render.c.s
.PHONY : src/graphics/render.s

# target to generate assembly for a file
src/graphics/render.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/graphics/render.c.s
.PHONY : src/graphics/render.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/main.c.s
.PHONY : src/main.c.s

src/math/vecs.o: src/math/vecs.c.o
.PHONY : src/math/vecs.o

# target to build an object file
src/math/vecs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/math/vecs.c.o
.PHONY : src/math/vecs.c.o

src/math/vecs.i: src/math/vecs.c.i
.PHONY : src/math/vecs.i

# target to preprocess a source file
src/math/vecs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/math/vecs.c.i
.PHONY : src/math/vecs.c.i

src/math/vecs.s: src/math/vecs.c.s
.PHONY : src/math/vecs.s

# target to generate assembly for a file
src/math/vecs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/math/vecs.c.s
.PHONY : src/math/vecs.c.s

src/physics/body.o: src/physics/body.c.o
.PHONY : src/physics/body.o

# target to build an object file
src/physics/body.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/physics/body.c.o
.PHONY : src/physics/body.c.o

src/physics/body.i: src/physics/body.c.i
.PHONY : src/physics/body.i

# target to preprocess a source file
src/physics/body.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/physics/body.c.i
.PHONY : src/physics/body.c.i

src/physics/body.s: src/physics/body.c.s
.PHONY : src/physics/body.s

# target to generate assembly for a file
src/physics/body.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/physics/body.c.s
.PHONY : src/physics/body.c.s

src/physics/circle.o: src/physics/circle.c.o
.PHONY : src/physics/circle.o

# target to build an object file
src/physics/circle.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/physics/circle.c.o
.PHONY : src/physics/circle.c.o

src/physics/circle.i: src/physics/circle.c.i
.PHONY : src/physics/circle.i

# target to preprocess a source file
src/physics/circle.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/physics/circle.c.i
.PHONY : src/physics/circle.c.i

src/physics/circle.s: src/physics/circle.c.s
.PHONY : src/physics/circle.s

# target to generate assembly for a file
src/physics/circle.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/physics/circle.c.s
.PHONY : src/physics/circle.c.s

src/physics/collision.o: src/physics/collision.c.o
.PHONY : src/physics/collision.o

# target to build an object file
src/physics/collision.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/physics/collision.c.o
.PHONY : src/physics/collision.c.o

src/physics/collision.i: src/physics/collision.c.i
.PHONY : src/physics/collision.i

# target to preprocess a source file
src/physics/collision.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/physics/collision.c.i
.PHONY : src/physics/collision.c.i

src/physics/collision.s: src/physics/collision.c.s
.PHONY : src/physics/collision.s

# target to generate assembly for a file
src/physics/collision.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/physics/collision.c.s
.PHONY : src/physics/collision.c.s

src/physics/physics.o: src/physics/physics.c.o
.PHONY : src/physics/physics.o

# target to build an object file
src/physics/physics.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/physics/physics.c.o
.PHONY : src/physics/physics.c.o

src/physics/physics.i: src/physics/physics.c.i
.PHONY : src/physics/physics.i

# target to preprocess a source file
src/physics/physics.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/physics/physics.c.i
.PHONY : src/physics/physics.c.i

src/physics/physics.s: src/physics/physics.c.s
.PHONY : src/physics/physics.s

# target to generate assembly for a file
src/physics/physics.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/physics/physics.c.s
.PHONY : src/physics/physics.c.s

src/stb/impl.o: src/stb/impl.c.o
.PHONY : src/stb/impl.o

# target to build an object file
src/stb/impl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/stb/impl.c.o
.PHONY : src/stb/impl.c.o

src/stb/impl.i: src/stb/impl.c.i
.PHONY : src/stb/impl.i

# target to preprocess a source file
src/stb/impl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/stb/impl.c.i
.PHONY : src/stb/impl.c.i

src/stb/impl.s: src/stb/impl.c.s
.PHONY : src/stb/impl.s

# target to generate assembly for a file
src/stb/impl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/stb/impl.c.s
.PHONY : src/stb/impl.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PhysicsEngine"
	@echo "... src/graphics/render.o"
	@echo "... src/graphics/render.i"
	@echo "... src/graphics/render.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/math/vecs.o"
	@echo "... src/math/vecs.i"
	@echo "... src/math/vecs.s"
	@echo "... src/physics/body.o"
	@echo "... src/physics/body.i"
	@echo "... src/physics/body.s"
	@echo "... src/physics/circle.o"
	@echo "... src/physics/circle.i"
	@echo "... src/physics/circle.s"
	@echo "... src/physics/collision.o"
	@echo "... src/physics/collision.i"
	@echo "... src/physics/collision.s"
	@echo "... src/physics/physics.o"
	@echo "... src/physics/physics.i"
	@echo "... src/physics/physics.s"
	@echo "... src/stb/impl.o"
	@echo "... src/stb/impl.i"
	@echo "... src/stb/impl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/oreo/Projects/physics-engine/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

